### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by scape1989** [ShichaoSun/math_seq2tree#1]
你好，可以给一下另外两个数据集嘛？ mawps和roth的

**Comment by ShichaoSun** [comment]
你好，我在小数据集合上的实验是在allArith这个数据集上做的，这个数据集链接是：https://github.com/CogComp/arithmetic/tree/master/data/allArith
你说的roth 应该指的是这个数据集。
MaWPS 可以参考这个链接：https://github.com/sroy9/mawps。
建议参考https://github.com/CogComp/arithmetic 这个仓库提供的说明

**Comment by dpbnnp** [comment]
您好请问能分享一下 mawps数据集吗，我用这两个链接下载不下来。我的邮箱是ziyliu@tencent.com

**Comment by ShichaoSun** [comment]
> 您好请问能分享一下 mawps数据集吗，我用这两个链接下载不下来。我的邮箱是[ziyliu@tencent.com](mailto:ziyliu@tencent.com)

不好意思，我没有在电脑上保留这个数据集
