### ISSUE TITLE
源代码细节

### ISSUE THREAD

**Issue by ICanFlyGFC** [ShichaoSun/math_seq2tree#4]
作者您好，我在阅读您的代码时不知道num_stack的作用是什么。为什么式子里面有的数字没有被替换成N*呢？
希望能解答下，感谢：）
   
`    for pair in pairs_trained:
        num_stack = []
        for word in pair[1]:
            temp_num = []
            flag_not = True
            if word not in output_lang.index2word:
                flag_not = False
                for i, j in enumerate(pair[2]):
                    if j == word:
                        temp_num.append(i)

            if not flag_not and len(temp_num) != 0:
                num_stack.append(temp_num)
            if not flag_not and len(temp_num) == 0:
                num_stack.append([_ for _ in range(len(pair[2]))])

        num_stack.reverse()
        input_cell = indexes_from_sentence(input_lang, pair[0])
        output_cell = indexes_from_sentence(output_lang, pair[1], tree)`

**Comment by ShichaoSun** [comment]
为什么式子里面有的数字没有被替换成N*呢？
因为有一些数字，需要直接生成，而不是从问题中获得，比如0， 1， pi,这些字符有特殊含义，是需要生成的。

num_stack 被用在https://github.com/ShichaoSun/math_seq2tree/blob/c3a1c5637894132ff53b390093ce4caf1bb063f5/src/train_and_evaluate.py#L201
目的是生成某一个数字，比如6， 但6在题目中出现了两次，要选择likelihood更大的那一个作为当前的输入。

**Comment by ICanFlyGFC** [comment]
感谢回答 ：) ，帮了大忙，目前还在扣源码中~~
