### ISSUE TITLE
关于generate_tree_input函数

### ISSUE THREAD

**Issue by mingliangzhang2018** [ShichaoSun/math_seq2tree#5]
模型对于重复数值处理函数generate_tree_input，这部分代码是不是有问题？
if decoder_output[i, num_start + num] > max_score:
    target[i] = num + num_start
    max_score = decoder_output[i, num_start + num]
decoder_output的输出是 操作个数+生成数个数+数值数（根据concat的顺序）， 这里num_start是操作个数，这里缺少生成数个数

**Comment by ShichaoSun** [comment]
https://github.com/ShichaoSun/math_seq2tree/blob/master/src/train_and_evaluate.py#L391 这一行表明了如何获得num_start:
即num_start = output_lang.n_words - copy_nums - 2
然后，https://github.com/ShichaoSun/math_seq2tree/blob/master/src/pre_data.py#L69 这一行写了如何获得output language 的index2word,
num_start 就是 操作个数+生成数个数 + ["PAD", "EOS"]
表示copy 数字起始的位置

**Comment by mingliangzhang2018** [comment]
> https://github.com/ShichaoSun/math_seq2tree/blob/master/src/train_and_evaluate.py#L391 这一行表明了如何获得num_start: 即num_start = output_lang.n_words - copy_nums - 2 然后，https://github.com/ShichaoSun/math_seq2tree/blob/master/src/pre_data.py#L69 这一行写了如何获得output language 的index2word, num_start 就是 操作个数+生成数个数 + ["PAD", "EOS"] 表示copy 数字起始的位置

谢谢您的及时回复，我发现https://github.com/ShichaoSun/math_seq2tree/blob/master/src/train_and_evaluate.py#L391
所在的函数train_attn并没有使用，模型跑的是train_tree函数。此外，output language 的index2word是
['*', '-', '/', '+', '^', '1', '3.14', 'N0', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6', ..., 'N14', 'UNK'], 并没有["PAD", "EOS"]

**Comment by ShichaoSun** [comment]
你说的对，我看错位置了，这个位置是生成树的output language，https://github.com/ShichaoSun/math_seq2tree/blob/d2310d08818ef073d75a3e736f2c0ee0c0aac02a/src/pre_data.py#L75 
,  https://github.com/ShichaoSun/math_seq2tree/blob/master/src/train_and_evaluate.py#L703 表明，num_start应该就是除了运算符以外的所有数字开始的id,
这个地方的设计，我依稀记得，有点太久远了，应该是因为比如，当前预测的数字是1，这个1 也在题目中出现了，那么，此时可以选择copy和生成，具体选择哪一种方式，要看打分的大小，所以，我这个位置没包括生成的数字

**Comment by mingliangzhang2018** [comment]
> 你说的对，我看错位置了，这个位置是生成树的output language，
> 
> https://github.com/ShichaoSun/math_seq2tree/blob/d2310d08818ef073d75a3e736f2c0ee0c0aac02a/src/pre_data.py#L75
> 
> 
> , https://github.com/ShichaoSun/math_seq2tree/blob/master/src/train_and_evaluate.py#L703 表明，num_start应该就是除了运算符以外的所有数字开始的id,
> 这个地方的设计，我依稀记得，有点太久远了，应该是因为比如，当前预测的数字是1，这个1 也在题目中出现了，那么，此时可以选择copy和生成，具体选择哪一种方式，要看打分的大小，所以，我这个位置没包括生成的数字

你好，我尝试着改变索引，发现结果没什么区别，我猜测是因为重复数字的情况占少数。

**Comment by ShichaoSun** [comment]
是这样的，我统计过，一方面是重复的很少，另一方面，预测到随便一个重复的，也不影响结果，所以，对结果几乎没啥影响，只是我写代码的时候，多考虑了一下
