### ISSUE TITLE
配置环境

### ISSUE THREAD

**Issue by yunjuyan** [ShichaoSun/math_seq2tree#7]
请问一下，这个配置环境cuda,cudnn是什么版本的？pytorch=0.4.1的版本现在好像下不到了，其它什么版本的pytorch也能跑吗？谢谢！

**Comment by ShichaoSun** [comment]
我觉得应该问题不大，高版本向下兼容做的还挺好的，你可以试一下，但愿应该没啥bug吧

**Comment by yunjuyan** [comment]
已收到
